package crud_parqueadero.interfaz;

import Clases.tickets;
import daos.DAOS;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class Actualizar extends javax.swing.JPanel {

    /**
     * Creates new form Actualizar
     */
    public Actualizar(DAOS daos) {
        initComponents();
        this.daos=daos;
        finalizadoMensaje.setVisible(false);
        errorMensaje.setVisible(false);
        jLabel13.setVisible(false);
        jLabel11.setVisible(false);
        jSeparator11.setVisible(false);
        jSeparator13.setVisible(false);
        Actualizar.setVisible(false);
        btnActualizar.setVisible(false);
        staffName.setVisible(false);
        hora_salida.setVisible(false);
        jLabel12.setVisible(false);
        costo.setVisible(false);
        jSeparator12.setVisible(false);
    }
    
    private DAOS daos;
    private tickets buscar;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JPanel();
        seleccionar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        t_number = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        btnActualizar = new javax.swing.JPanel();
        Actualizar = new javax.swing.JLabel();
        staffName = new javax.swing.JLabel();
        errorMensaje = new javax.swing.JLabel();
        hora_salida = new javax.swing.JLabel();
        finalizadoMensaje = new javax.swing.JLabel();
        costo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(0, 102, 255));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        seleccionar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        seleccionar.setForeground(new java.awt.Color(0, 0, 0));
        seleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preview.png"))); // NOI18N
        seleccionar.setText("Buscar");
        seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleccionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleccionarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 130, 40));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 500, 10));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buscar un tiquete  ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        t_number.setBackground(new java.awt.Color(255, 255, 255));
        t_number.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        t_number.setForeground(new java.awt.Color(153, 153, 153));
        t_number.setText("Ingrese el numero");
        t_number.setBorder(null);
        t_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_numberMouseClicked(evt);
            }
        });
        jPanel2.add(t_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero de tiquete");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 500, 10));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Costo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 220, 10));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Staff de salida");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 220, 10));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 255));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
        });

        Actualizar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Actualizar.setForeground(new java.awt.Color(0, 0, 0));
        Actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 130, 40));

        staffName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        staffName.setForeground(new java.awt.Color(0, 0, 0));
        staffName.setText("Staff");
        jPanel2.add(staffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        errorMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        errorMensaje.setForeground(new java.awt.Color(255, 0, 0));
        errorMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-de-exclamacion (1).png"))); // NOI18N
        errorMensaje.setText("Error");
        jPanel2.add(errorMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        hora_salida.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        hora_salida.setForeground(new java.awt.Color(0, 0, 0));
        hora_salida.setText("Hora de salida");
        jPanel2.add(hora_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        finalizadoMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        finalizadoMensaje.setForeground(new java.awt.Color(51, 255, 51));
        finalizadoMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cheque (1).png"))); // NOI18N
        finalizadoMensaje.setText("Ticket actualizado");
        jPanel2.add(finalizadoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        costo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        costo.setForeground(new java.awt.Color(0, 0, 0));
        costo.setText("Costo");
        jPanel2.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Hora de salida");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseEntered

    private void ActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseExited
        btnActualizar.setBackground(new Color(0, 102, 255));
        Actualizar.setForeground(Color.BLACK);
    }//GEN-LAST:event_ActualizarMouseExited

    private void ActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseEntered
        btnActualizar.setBackground(new Color(66, 172, 232));
        Actualizar.setForeground(Color.white);
    }//GEN-LAST:event_ActualizarMouseEntered

    private void t_numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_numberMouseClicked
        if(t_number.getText().equals("Ingrese el numero")){
            t_number.setText("");
        }
        t_number.setForeground(Color.black);
    }//GEN-LAST:event_t_numberMouseClicked

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(66, 172, 232));
        seleccionar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(66, 172, 232));
        seleccionar.setForeground(Color.white);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void seleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMouseExited
        btnBuscar.setBackground(new Color(0, 102, 255));
        seleccionar.setForeground(Color.BLACK);
    }//GEN-LAST:event_seleccionarMouseExited

    private void seleccionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMouseEntered
        btnBuscar.setBackground(new Color(66, 172, 232));
        seleccionar.setForeground(Color.white);
    }//GEN-LAST:event_seleccionarMouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        if(t_number.getText().equals("")){
            t_number.setText("Ingrese el numero");
            t_number.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMouseClicked
        errorMensaje.setVisible(false);
        finalizadoMensaje.setVisible(false);
        String capNumber=t_number.getText();
        if(capNumber.equals("Ingrese el numero") || capNumber.length()>10){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Numero no valido");
            return;
        }
        try {
            buscar = daos.buscar(capNumber);
            if(buscar.getCLIENT_Id()==null){
                errorMensaje.setVisible(true);
                errorMensaje.setText("Ticekt no valido");
                return;
            }
            if(buscar.getDeparture_time()!=null){
                errorMensaje.setVisible(true);
                errorMensaje.setText("El ticket no se puede actualizar");
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel13.setVisible(true);
        jLabel11.setVisible(true);
        jSeparator11.setVisible(true);
        jSeparator13.setVisible(true);
        Actualizar.setVisible(true);
        btnActualizar.setVisible(true);
        staffName.setVisible(true);
        hora_salida.setVisible(true);
        jLabel12.setVisible(true);
        costo.setVisible(true);
        jSeparator12.setVisible(true);
    }//GEN-LAST:event_seleccionarMouseClicked

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
        finalizadoMensaje.setVisible(true);
        buscar.setSTAFF_out(daos.getSelectedStaff().getId());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        buscar.setDeparture_time(dtf.format(LocalDateTime.now()));
        
        staffName.setText(daos.getSelectedStaff().getName());
        hora_salida.setText(dtf.format(LocalDateTime.now()));
        
        try {
            buscar = daos.actualizar(buscar);
        } catch (SQLException ex) {
            Logger.getLogger(Actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        costo.setText(buscar.getCost());
        btnActualizar.setVisible(false);
        
        
    }//GEN-LAST:event_ActualizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualizar;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JLabel costo;
    private javax.swing.JLabel errorMensaje;
    private javax.swing.JLabel finalizadoMensaje;
    private javax.swing.JLabel hora_salida;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel seleccionar;
    private javax.swing.JLabel staffName;
    private javax.swing.JTextField t_number;
    // End of variables declaration//GEN-END:variables
}
