
package crud_parqueadero.interfaz;

import Clases.tickets;
import daos.DAOS;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Daniel Alzate
 */
public class Borrar extends javax.swing.JPanel {

    /**
     * Creates new form Borrar
     */
    public Borrar(DAOS daos) {
        initComponents();
        this.daos=daos;
        finalizadoMensaje.setVisible(false);
        errorMensaje.setVisible(false);
        jLabel16.setVisible(false);
        si.setVisible(false);
        no.setVisible(false);
        btnSi.setVisible(false);
        btnNo.setVisible(false);
    }
    
    private DAOS daos;
    private String capId;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnBuscar1 = new javax.swing.JPanel();
        seleccionar1 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        t_number1 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        btnNo = new javax.swing.JPanel();
        no = new javax.swing.JLabel();
        btnSi = new javax.swing.JPanel();
        si = new javax.swing.JLabel();
        errorMensaje = new javax.swing.JLabel();
        finalizadoMensaje = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar1.setBackground(new java.awt.Color(0, 102, 255));
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscar1MouseExited(evt);
            }
        });

        seleccionar1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        seleccionar1.setForeground(new java.awt.Color(0, 0, 0));
        seleccionar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preview.png"))); // NOI18N
        seleccionar1.setText("Buscar");
        seleccionar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleccionar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleccionar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscar1Layout = new javax.swing.GroupLayout(btnBuscar1);
        btnBuscar1.setLayout(btnBuscar1Layout);
        btnBuscar1Layout.setHorizontalGroup(
            btnBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnBuscar1Layout.setVerticalGroup(
            btnBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 130, 40));
        jPanel4.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 500, 10));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Borrar un tiquete  ");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        t_number1.setBackground(new java.awt.Color(255, 255, 255));
        t_number1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        t_number1.setForeground(new java.awt.Color(153, 153, 153));
        t_number1.setText("Ingrese el numero");
        t_number1.setBorder(null);
        t_number1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_number1MouseClicked(evt);
            }
        });
        jPanel4.add(t_number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 30));
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 30));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("¿Seguro que desea eliminar el ticket?");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));
        jPanel4.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 500, 10));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Numero de tiquete");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnNo.setBackground(new java.awt.Color(0, 102, 255));
        btnNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoMouseExited(evt);
            }
        });

        no.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        no.setForeground(new java.awt.Color(0, 0, 0));
        no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/forbidden.png"))); // NOI18N
        no.setText("NO");
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNoLayout = new javax.swing.GroupLayout(btnNo);
        btnNo.setLayout(btnNoLayout);
        btnNoLayout.setHorizontalGroup(
            btnNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(no, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnNoLayout.setVerticalGroup(
            btnNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 130, 40));

        btnSi.setBackground(new java.awt.Color(0, 102, 255));
        btnSi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiMouseExited(evt);
            }
        });

        si.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        si.setForeground(new java.awt.Color(0, 0, 0));
        si.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        si.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete-file.png"))); // NOI18N
        si.setText("SI");
        si.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSiLayout = new javax.swing.GroupLayout(btnSi);
        btnSi.setLayout(btnSiLayout);
        btnSiLayout.setHorizontalGroup(
            btnSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(si, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnSiLayout.setVerticalGroup(
            btnSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(si, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel4.add(btnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 130, 40));

        errorMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        errorMensaje.setForeground(new java.awt.Color(255, 0, 0));
        errorMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-de-exclamacion (1).png"))); // NOI18N
        errorMensaje.setText("Error");
        jPanel4.add(errorMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        finalizadoMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        finalizadoMensaje.setForeground(new java.awt.Color(51, 255, 51));
        finalizadoMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cheque (1).png"))); // NOI18N
        finalizadoMensaje.setText("Ticket borrado");
        jPanel4.add(finalizadoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionar1MouseEntered
        btnBuscar1.setBackground(new Color(66, 172, 232));
        seleccionar1.setForeground(Color.white);
    }//GEN-LAST:event_seleccionar1MouseEntered

    private void seleccionar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionar1MouseExited
        btnBuscar1.setBackground(new Color(0, 102, 255));
        seleccionar1.setForeground(Color.BLACK);
    }//GEN-LAST:event_seleccionar1MouseExited

    private void btnBuscar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1MouseEntered

    private void btnBuscar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1MouseExited

    private void t_number1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_number1MouseClicked
        if(t_number1.getText().equals("Ingrese el numero")){
            t_number1.setText("");
            t_number1.setForeground(Color.black);
        }
    }//GEN-LAST:event_t_number1MouseClicked

    private void noMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseEntered
        btnNo.setBackground(new Color(66, 172, 232));
        no.setForeground(Color.white);
    }//GEN-LAST:event_noMouseEntered

    private void noMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseExited
        btnNo.setBackground(new Color(0, 102, 255));
        no.setForeground(Color.BLACK);
    }//GEN-LAST:event_noMouseExited

    private void btnNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoMouseEntered

    private void btnNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoMouseExited

    private void siMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siMouseEntered
        btnSi.setBackground(new Color(66, 172, 232));
        si.setForeground(Color.white);
    }//GEN-LAST:event_siMouseEntered

    private void siMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siMouseExited
        btnSi.setBackground(new Color(0, 102, 255));
        si.setForeground(Color.BLACK);
    }//GEN-LAST:event_siMouseExited

    private void btnSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiMouseEntered

    private void btnSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiMouseExited

    private void seleccionar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionar1MouseClicked

        errorMensaje.setVisible(false);
        finalizadoMensaje.setVisible(false);
        String capNumber=t_number1.getText();
        if(capNumber.equals("Ingrese el numero") || capNumber.length()>10){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Numero no valido");
            return;
        }
        try {
            tickets buscar = daos.buscar(capNumber);
            if(buscar.getDeparture_time()==null){
                errorMensaje.setVisible(true);
                errorMensaje.setText("El ticket debe ser cobrado primero");
                return;
            }
            if(buscar.getCLIENT_Id()==null){
                errorMensaje.setVisible(true);
                errorMensaje.setText("Ticket no valido");
                jLabel16.setVisible(false);
                si.setVisible(false);
                no.setVisible(false);
                btnSi.setVisible(false);
                btnNo.setVisible(false);
                finalizadoMensaje.setVisible(false);
                return;
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Borrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel16.setVisible(true);
        si.setVisible(true);
        no.setVisible(true);
        btnSi.setVisible(true);
        btnNo.setVisible(true);
        capId=capNumber;
    }//GEN-LAST:event_seleccionar1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        if(t_number1.getText().equals("")){
            t_number1.setText("Ingrese el numero");
            t_number1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void siMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siMouseClicked
        finalizadoMensaje.setVisible(true);
        errorMensaje.setVisible(false);
        jLabel16.setVisible(false);
        si.setVisible(false);
        no.setVisible(false);
        btnSi.setVisible(false);
        btnNo.setVisible(false);
        try {
            daos.borrar(capId);
        } catch (SQLException ex) {
            Logger.getLogger(Borrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siMouseClicked

    private void noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseClicked
        errorMensaje.setVisible(false);
        jLabel16.setVisible(false);
        si.setVisible(false);
        no.setVisible(false);
        btnSi.setVisible(false);
        btnNo.setVisible(false);
        capId="";
    }//GEN-LAST:event_noMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar1;
    private javax.swing.JPanel btnNo;
    private javax.swing.JPanel btnSi;
    private javax.swing.JLabel errorMensaje;
    private javax.swing.JLabel finalizadoMensaje;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JLabel no;
    private javax.swing.JLabel seleccionar1;
    private javax.swing.JLabel si;
    private javax.swing.JTextField t_number1;
    // End of variables declaration//GEN-END:variables
}
