package crud_parqueadero.interfaz;

import Clases.tickets;
import daos.DAOS;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Daniel Alzate 
 */
public class Buscar extends javax.swing.JPanel {

    /**
     * Creates new form Busca
     */
    public Buscar(DAOS daos) {
        initComponents();
        errorMensaje.setVisible(false);
        this.daos=daos;
        jLabel9.setVisible(false);
        jLabel5.setVisible(false);
        jLabel10.setVisible(false);
        jLabel6.setVisible(false);
        jLabel11.setVisible(false);
        jLabel7.setVisible(false);
        jLabel12.setVisible(false);
        jLabel8.setVisible(false);
        jLabel13.setVisible(false);
        jLabel3.setVisible(false);
        
        jSeparator9.setVisible(false);
        jSeparator1.setVisible(false);
        jSeparator10.setVisible(false);
        jSeparator6.setVisible(false);
        jSeparator11.setVisible(false);
        jSeparator7.setVisible(false);
        jSeparator12.setVisible(false);
        jSeparator8.setVisible(false);
        jSeparator13.setVisible(false);
        jSeparator4.setVisible(false);
        
        numero.setVisible(false);
        celda.setVisible(false);
        entry_tyme.setVisible(false);
        placa.setVisible(false);
        departure_time.setVisible(false);
        cedula.setVisible(false);
        staff_in.setVisible(false);
        costo.setVisible(false);
        staff_out.setVisible(false);
        tarifa.setVisible(false);
    }
    
    private DAOS daos;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBuscar = new javax.swing.JPanel();
        seleccionar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        t_number = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        numero = new javax.swing.JLabel();
        entry_tyme = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        departure_time = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        staff_in = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        staff_out = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        celda = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        costo = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        tarifa = new javax.swing.JLabel();
        errorMensaje = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 220, 10));

        btnBuscar.setBackground(new java.awt.Color(0, 102, 255));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        seleccionar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        seleccionar.setForeground(new java.awt.Color(0, 0, 0));
        seleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preview.png"))); // NOI18N
        seleccionar.setText("Buscar");
        seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleccionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleccionarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccionarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 130, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 500, 10));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buscar un tiquete  ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        t_number.setBackground(new java.awt.Color(255, 255, 255));
        t_number.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        t_number.setForeground(new java.awt.Color(153, 153, 153));
        t_number.setText("Ingrese el numero");
        t_number.setBorder(null);
        t_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_numberMouseClicked(evt);
            }
        });
        jPanel1.add(t_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 220, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 10));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Id de tarifa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero de tiquete");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Celda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 500, 10));

        numero.setForeground(new java.awt.Color(0, 0, 0));
        numero.setText("Numero");
        jPanel1.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        entry_tyme.setForeground(new java.awt.Color(0, 0, 0));
        entry_tyme.setText("Hora de entrada");
        jPanel1.add(entry_tyme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Placa");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        departure_time.setForeground(new java.awt.Color(0, 0, 0));
        departure_time.setText("Hora de salida");
        jPanel1.add(departure_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 220, 10));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cedula del cliente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        staff_in.setForeground(new java.awt.Color(0, 0, 0));
        staff_in.setText("Staff de entrada");
        jPanel1.add(staff_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 220, 10));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Costo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        staff_out.setForeground(new java.awt.Color(0, 0, 0));
        staff_out.setText("Staff de salida");
        jPanel1.add(staff_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 220, 10));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Numero");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        celda.setForeground(new java.awt.Color(0, 0, 0));
        celda.setText("Celda");
        jPanel1.add(celda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 220, 10));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Hora de entrada");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        placa.setForeground(new java.awt.Color(0, 0, 0));
        placa.setText("Placa");
        jPanel1.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, 10));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Hora de salida");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cedula.setForeground(new java.awt.Color(0, 0, 0));
        cedula.setText("Cedula");
        jPanel1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 220, 10));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Staff de entrada");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        costo.setForeground(new java.awt.Color(0, 0, 0));
        costo.setText("Costo");
        jPanel1.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 220, 10));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Staff de salida");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 220, 10));

        tarifa.setText("Tarifa");
        jPanel1.add(tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        errorMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        errorMensaje.setForeground(new java.awt.Color(255, 0, 0));
        errorMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-de-exclamacion (1).png"))); // NOI18N
        errorMensaje.setText("Error");
        jPanel1.add(errorMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMouseEntered
        btnBuscar.setBackground(new Color(66, 172, 232));
        seleccionar.setForeground(Color.white);
    }//GEN-LAST:event_seleccionarMouseEntered

    private void seleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMouseExited
        btnBuscar.setBackground(new Color(0, 102, 255));
        seleccionar.setForeground(Color.BLACK);
    }//GEN-LAST:event_seleccionarMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        System.out.println("----");
        btnBuscar.setBackground(new Color(66, 172, 232));
        seleccionar.setForeground(Color.white);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(66, 172, 232));
        seleccionar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnBuscarMouseExited

    private void t_numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_numberMouseClicked
        if(t_number.getText().equals("Ingrese el numero")){
            t_number.setText("");
        }
        t_number.setForeground(Color.black);
    }//GEN-LAST:event_t_numberMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if(t_number.getText().equals("")){
            t_number.setText("Ingrese le numero");
            t_number.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void seleccionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMousePressed
        //validacion 
        errorMensaje.setVisible(false);
        String capNumber=t_number.getText();
        if(capNumber.equals("Ingrese el numero") || capNumber.length()>10){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Numero no valido");
            return;
        }
        
        try {
            tickets buscar = daos.buscar(capNumber);
            if(buscar.getCLIENT_Id()==null){
                errorMensaje.setVisible(true);
                errorMensaje.setText("El ticket no existe");
                jLabel9.setVisible(false);
                jLabel5.setVisible(false);
                jLabel10.setVisible(false);
                jLabel6.setVisible(false);
                jLabel11.setVisible(false);
                jLabel7.setVisible(false);
                jLabel12.setVisible(false);
                jLabel8.setVisible(false);
                jLabel13.setVisible(false);
                jLabel3.setVisible(false);

                jSeparator9.setVisible(false);
                jSeparator1.setVisible(false);
                jSeparator10.setVisible(false);
                jSeparator6.setVisible(false);
                jSeparator11.setVisible(false);
                jSeparator7.setVisible(false);
                jSeparator12.setVisible(false);
                jSeparator8.setVisible(false);
                jSeparator13.setVisible(false);
                jSeparator4.setVisible(false);

                numero.setVisible(false);
                celda.setVisible(false);
                entry_tyme.setVisible(false);
                placa.setVisible(false);
                departure_time.setVisible(false);
                cedula.setVisible(false);
                staff_in.setVisible(false);
                costo.setVisible(false);
                staff_out.setVisible(false);
                tarifa.setVisible(false);
                return;
            }
            
            jLabel9.setVisible(true);
            jLabel5.setVisible(true);
            jLabel10.setVisible(true);
            jLabel6.setVisible(true);
            jLabel11.setVisible(true);
            jLabel7.setVisible(true);
            jLabel12.setVisible(true);
            jLabel8.setVisible(true);
            jLabel13.setVisible(true);
            jLabel3.setVisible(true);

            jSeparator9.setVisible(true);
            jSeparator1.setVisible(true);
            jSeparator10.setVisible(true);
            jSeparator6.setVisible(true);
            jSeparator11.setVisible(true);
            jSeparator7.setVisible(true);
            jSeparator12.setVisible(true);
            jSeparator8.setVisible(true);
            jSeparator13.setVisible(true);
            jSeparator4.setVisible(true);

            numero.setVisible(true);
            celda.setVisible(true);
            entry_tyme.setVisible(true);
            placa.setVisible(true);
            departure_time.setVisible(true);
            cedula.setVisible(true);
            staff_in.setVisible(true);
            costo.setVisible(true);
            staff_out.setVisible(true);
            tarifa.setVisible(true);
            
            numero.setText(buscar.getT_number());
            celda.setText(String.valueOf(buscar.getPARKING_CELL()));
            entry_tyme.setText(buscar.getEntry_time());
            placa.setText(buscar.getVEHICLE_License_plate());
            departure_time.setText(buscar.getDeparture_time());
            cedula.setText(buscar.getCLIENT_Id());
            staff_in.setText(buscar.getSTAFF_in());
            costo.setText(buscar.getCost());
            staff_out.setText(buscar.getSTAFF_out());
            tarifa.setText(buscar.getRATES_Id());
        } catch (SQLException ex) {
            Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_seleccionarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel celda;
    private javax.swing.JLabel costo;
    private javax.swing.JLabel departure_time;
    private javax.swing.JLabel entry_tyme;
    private javax.swing.JLabel errorMensaje;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel seleccionar;
    private javax.swing.JLabel staff_in;
    private javax.swing.JLabel staff_out;
    private javax.swing.JTextField t_number;
    private javax.swing.JLabel tarifa;
    // End of variables declaration//GEN-END:variables
}
