package crud_parqueadero.interfaz;

import daos.DAOS;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Daniel Alzate 
 */
public class NuevoCliente extends javax.swing.JPanel {

    /**
     * Creates new form pp
     * @param clientes
     */
    public NuevoCliente(DAOS daos) {
        initComponents();
        this.daos=daos;
        errorMensaje.setVisible(false);
        finalizadoMensaje.setVisible(false);
    }
    
    private DAOS daos;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        cellphone = new javax.swing.JTextField();
        btnCrear = new javax.swing.JPanel();
        crear = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        errorMensaje = new javax.swing.JLabel();
        finalizadoMensaje = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(510, 470));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 500, 10));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Crea un nuevo cliente ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(153, 153, 153));
        id.setText("Ingrese la identificacion");
        id.setBorder(null);
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idMouseClicked(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 220, 30));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(153, 153, 153));
        name.setText("Ingrese el nombre");
        name.setBorder(null);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 10));

        cellphone.setBackground(new java.awt.Color(255, 255, 255));
        cellphone.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cellphone.setForeground(new java.awt.Color(153, 153, 153));
        cellphone.setText("Ingrese el numero de telefono");
        cellphone.setBorder(null);
        cellphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cellphoneMouseClicked(evt);
            }
        });
        cellphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellphoneActionPerformed(evt);
            }
        });
        jPanel2.add(cellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 220, 30));

        btnCrear.setBackground(new java.awt.Color(0, 102, 255));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearMousePressed(evt);
            }
        });

        crear.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        crear.setForeground(new java.awt.Color(0, 0, 0));
        crear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-user.png"))); // NOI18N
        crear.setText("Crear Cliente");

        javax.swing.GroupLayout btnCrearLayout = new javax.swing.GroupLayout(btnCrear);
        btnCrear.setLayout(btnCrearLayout);
        btnCrearLayout.setHorizontalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnCrearLayout.setVerticalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 130, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Teléfono");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Id");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        errorMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        errorMensaje.setForeground(new java.awt.Color(255, 0, 0));
        errorMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-de-exclamacion (1).png"))); // NOI18N
        errorMensaje.setText("Error");
        jPanel2.add(errorMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        finalizadoMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        finalizadoMensaje.setForeground(new java.awt.Color(51, 255, 51));
        finalizadoMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cheque (1).png"))); // NOI18N
        finalizadoMensaje.setText("Cliente creado");
        jPanel2.add(finalizadoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseClicked
        if(id.getText().equals("Ingrese la identificacion")){
            id.setText("");
        }
        id.setForeground(Color.black);
        if(name.getText().equals("")){
            name.setText("Ingrese el nombre");
            name.setForeground(new Color(153, 153, 153));
        }
        if(cellphone.getText().equals("")){
            cellphone.setText("Ingrese el numero de telefono");
            cellphone.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_idMouseClicked

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        if(name.getText().equals("Ingrese el nombre")){
            name.setText("");
        }
        name.setForeground(Color.black);
        if(id.getText().equals("")){
            id.setText("Ingrese la identificacion");
            id.setForeground(new Color(153, 153, 153));
        }
        if(cellphone.getText().equals("")){
            cellphone.setText("Ingrese el numero de telefono");
            cellphone.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_nameMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void cellphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cellphoneMouseClicked
        if(cellphone.getText().equals("Ingrese el numero de telefono")){
            cellphone.setText("");
        }
        cellphone.setForeground(Color.black);
        if(id.getText().equals("")){
            id.setText("Ingrese la identificacion");
            id.setForeground(new Color(153, 153, 153));
        }
        if(name.getText().equals("")){
            name.setText("Ingrese el nombre");
            name.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_cellphoneMouseClicked

    private void cellphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellphoneActionPerformed

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        btnCrear.setBackground(new Color(66, 172, 232));
        crear.setForeground(Color.white);
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        btnCrear.setBackground(new Color(0, 102, 255));
        crear.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCrearMouseExited

    private void btnCrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMousePressed
        errorMensaje.setVisible(false);
        finalizadoMensaje.setVisible(false);
        String capId= id.getText();
        if(capId.equals("Ingrese la identificacion") || capId.length()!=10 || !capId.matches("^[1-9]{1}[0-9]{9}$")){
            errorMensaje.setText("Identificacion no valida");
            errorMensaje.setVisible(true);
            return;
        }
        String capNombre = name.getText();
        if(capNombre.equals("Ingrese el nombre") || capNombre.length()>12){
            errorMensaje.setText("Nombre no valido");
            errorMensaje.setVisible(true);
            return;
        }
        String capTelefono = cellphone.getText();
        if(capTelefono.equals("Ingrese el numero de telefono") || capTelefono.length()!=10 || !capTelefono.matches("^[1-9]{1}[0-9]{9}$")){
            errorMensaje.setText("Numero de telefono no valido");
            errorMensaje.setVisible(true);
            return;
        }
        daos.crearCliente(capId, capNombre, capTelefono);
        finalizadoMensaje.setVisible(true);
        id.setText("Ingrese la identificacion");
        id.setForeground(new Color(153, 153, 153));
        name.setText("Ingrese el nombre");
        name.setForeground(new Color(153, 153, 153));
        cellphone.setText("Ingrese el numero de telefono");
        cellphone.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_btnCrearMousePressed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCrear;
    private javax.swing.JTextField cellphone;
    private javax.swing.JLabel crear;
    private javax.swing.JLabel errorMensaje;
    private javax.swing.JLabel finalizadoMensaje;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
