/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_parqueadero.interfaz;

import Clases.tickets;
import SQL.InsertarTicket;
import daos.DAOS;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class NuevoTicket extends javax.swing.JPanel {

    /**
     * Creates new form Cliente
     * @param daos
     * @throws java.sql.SQLException
     */
    public NuevoTicket(DAOS daos) throws SQLException {
        initComponents();
        errorMensaje.setVisible(false);
        alertMensaje.setVisible(false);
        finalizadoMensaje.setVisible(false);
        this.daos=daos;
        celdas = this.daos.getCeldasDis();
        placas = this.daos.getPlacas();
        clientes = this.daos.getClientes();
        
        if(celdas.isEmpty()){
            alertMensaje.setVisible(true);
            btnCrear.setVisible(false);
        }
        
        staff.setText(this.daos.getSelectedStaff().getName());
        
        for(int i=0; i<celdas.size(); i++){
            CeldaSelector.addItem(celdas.get(i));
        }
        for(int i=0; i<placas.size(); i++){
            PlacaSelector.addItem(placas.get(i));
        }
        for(int i=0; i<clientes.size(); i++){
            ClienteSelector.addItem(clientes.get(i));
        }
        
    }
    
    private DAOS daos;
    private ArrayList<String> celdas;
    private ArrayList<String> placas;
    private ArrayList<String> clientes;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ClienteSelector = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnCrear = new javax.swing.JPanel();
        crear = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        CeldaSelector = new javax.swing.JComboBox<>();
        PlacaSelector = new javax.swing.JComboBox<>();
        errorMensaje = new javax.swing.JLabel();
        staff = new javax.swing.JLabel();
        alertMensaje = new javax.swing.JLabel();
        finalizadoMensaje = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(510, 470));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, 20));

        ClienteSelector.setBackground(new java.awt.Color(255, 255, 255));
        ClienteSelector.setEditable(true);
        ClienteSelector.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ClienteSelector.setForeground(new java.awt.Color(0, 0, 0));
        ClienteSelector.setMaximumRowCount(20);
        ClienteSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un cliente" }));
        ClienteSelector.setBorder(null);
        ClienteSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteSelectorActionPerformed(evt);
            }
        });
        jPanel1.add(ClienteSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 10));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Crea un nuevo ticket ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 220, 20));

        btnCrear.setBackground(new java.awt.Color(0, 102, 255));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearMousePressed(evt);
            }
        });

        crear.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        crear.setForeground(new java.awt.Color(0, 0, 0));
        crear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        crear.setText("Crear Ticket");

        javax.swing.GroupLayout btnCrearLayout = new javax.swing.GroupLayout(btnCrear);
        btnCrear.setLayout(btnCrearLayout);
        btnCrearLayout.setHorizontalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCrearLayout.setVerticalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 130, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Placa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cliente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Celda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Staff");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 220, 20));

        CeldaSelector.setBackground(new java.awt.Color(255, 255, 255));
        CeldaSelector.setEditable(true);
        CeldaSelector.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        CeldaSelector.setForeground(new java.awt.Color(0, 0, 0));
        CeldaSelector.setMaximumRowCount(20);
        CeldaSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una celda" }));
        CeldaSelector.setBorder(null);
        CeldaSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeldaSelectorActionPerformed(evt);
            }
        });
        jPanel1.add(CeldaSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, -1));

        PlacaSelector.setBackground(new java.awt.Color(255, 255, 255));
        PlacaSelector.setEditable(true);
        PlacaSelector.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        PlacaSelector.setForeground(new java.awt.Color(0, 0, 0));
        PlacaSelector.setMaximumRowCount(20);
        PlacaSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una placa" }));
        PlacaSelector.setBorder(null);
        PlacaSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaSelectorActionPerformed(evt);
            }
        });
        jPanel1.add(PlacaSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 240, -1));

        errorMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        errorMensaje.setForeground(new java.awt.Color(255, 0, 0));
        errorMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-de-exclamacion (1).png"))); // NOI18N
        errorMensaje.setText("Error");
        jPanel1.add(errorMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        staff.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        staff.setForeground(new java.awt.Color(0, 0, 0));
        staff.setText("Staff");
        jPanel1.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        alertMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        alertMensaje.setForeground(new java.awt.Color(255, 204, 0));
        alertMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-de-exclamacion (2).png"))); // NOI18N
        alertMensaje.setText("Actualmete no hay celdas disponibles");
        jPanel1.add(alertMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        finalizadoMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        finalizadoMensaje.setForeground(new java.awt.Color(51, 255, 51));
        finalizadoMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cheque (1).png"))); // NOI18N
        finalizadoMensaje.setText("Ticket creado");
        jPanel1.add(finalizadoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteSelectorActionPerformed

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        btnCrear.setBackground(new Color(66, 172, 232));
        crear.setForeground(Color.white);
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        btnCrear.setBackground(new Color(0, 102, 255));
        crear.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCrearMouseExited

    private void CeldaSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeldaSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CeldaSelectorActionPerformed

    private void PlacaSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaSelectorActionPerformed

    private void btnCrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMousePressed
        errorMensaje.setVisible(false);
        alertMensaje.setVisible(false);
        finalizadoMensaje.setVisible(false);
        if(CeldaSelector.getSelectedItem().toString().equals("Seleccione una celda")){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Seleccione una celda");
            return;
        }
        
        if(PlacaSelector.getSelectedItem().toString().equals("Seleccione una placa")){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Seleccione una placa");
            return;
        }
        
        if(ClienteSelector.getSelectedItem().toString().equals("Seleccione un cliente")){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Seleccione un cliente");
            return;
        }
        
        //conexiion con la base 
        tickets nuevo = new tickets();
        nuevo.setCLIENT_Id(clientes.get(ClienteSelector.getSelectedIndex()-1));
        nuevo.setEntry_time(InsertarTicket.fechaentrada());
        nuevo.setPARKING_CELL(Integer.parseInt(celdas.get(CeldaSelector.getSelectedIndex()-1)));
        nuevo.setSTAFF_in(daos.getSelectedStaff().getId());
        nuevo.setVEHICLE_License_plate(placas.get(PlacaSelector.getSelectedIndex()-1));
        try {
            daos.crearTicket(nuevo);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        finalizadoMensaje.setVisible(true);
        try {
            actualizarCeldas();
        } catch (SQLException ex) {
            Logger.getLogger(NuevoTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
        CeldaSelector.setSelectedIndex(0);
        PlacaSelector.setSelectedIndex(0);
        ClienteSelector.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnCrearMousePressed

    private void actualizarCeldas() throws SQLException{
        celdas.clear();
        CeldaSelector.removeAllItems();
        celdas = this.daos.getCeldasDis();
        CeldaSelector.addItem("Seleccione una celda");
        if(celdas.isEmpty()){
            alertMensaje.setVisible(true);
            btnCrear.setVisible(false);
        }
        for(int i=0; i<celdas.size(); i++){
            CeldaSelector.addItem(celdas.get(i));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CeldaSelector;
    private javax.swing.JComboBox<String> ClienteSelector;
    private javax.swing.JComboBox<String> PlacaSelector;
    private javax.swing.JLabel alertMensaje;
    private javax.swing.JPanel btnCrear;
    private javax.swing.JLabel crear;
    private javax.swing.JLabel errorMensaje;
    private javax.swing.JLabel finalizadoMensaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel staff;
    // End of variables declaration//GEN-END:variables
}
