/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_parqueadero.interfaz;

import Clases.Brands;
import Clases.Colors;
import Clases.Types;
import Clases.Vehiculos;
import daos.DAOS;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class NuevoVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form Vehiculo
     * @param daos
     */
    public NuevoVehiculo(DAOS daos) throws SQLException {
        initComponents();
        errorMensaje.setVisible(false);
        finalizadoMensaje.setVisible(false);
        this.daos=daos;
        marcas = this.daos.getMarcas();
        colores = this.daos.getColores();
        tipos = this.daos.getTipos();     
        for(int i=0; i<marcas.size(); i++){
            MarcaSelector.addItem(marcas.get(i).getName());
        }
        
        for(int i=0; i<colores.size(); i++){
            ColorSelector.addItem(colores.get(i).getName());
        }
        
        for(int i=0; i<tipos.size(); i++){
            TipoSelector.addItem(tipos.get(i).getName());
        }
    }
    
    private DAOS daos;
    ArrayList<Brands> marcas;
    ArrayList<Colors> colores;
    ArrayList<Types> tipos;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        ColorSelector = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnCrear = new javax.swing.JPanel();
        crear = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        MarcaSelector = new javax.swing.JComboBox<>();
        TipoSelector = new javax.swing.JComboBox<>();
        errorMensaje = new javax.swing.JLabel();
        finalizadoMensaje = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(510, 470));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, 30));

        ColorSelector.setBackground(new java.awt.Color(255, 255, 255));
        ColorSelector.setEditable(true);
        ColorSelector.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ColorSelector.setForeground(new java.awt.Color(0, 0, 0));
        ColorSelector.setMaximumRowCount(20);
        ColorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un color" }));
        ColorSelector.setBorder(null);
        ColorSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorSelectorActionPerformed(evt);
            }
        });
        jPanel1.add(ColorSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 240, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 500, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Crea un nuevo vehiculo ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        placa.setBackground(new java.awt.Color(255, 255, 255));
        placa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        placa.setForeground(new java.awt.Color(153, 153, 153));
        placa.setText("Ingrese la placa");
        placa.setBorder(null);
        placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placaMouseClicked(evt);
            }
        });
        jPanel1.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 220, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 30));

        btnCrear.setBackground(new java.awt.Color(0, 102, 255));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });

        crear.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        crear.setForeground(new java.awt.Color(0, 0, 0));
        crear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        crear.setText("Crear Vehiculo");

        javax.swing.GroupLayout btnCrearLayout = new javax.swing.GroupLayout(btnCrear);
        btnCrear.setLayout(btnCrearLayout);
        btnCrearLayout.setHorizontalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCrearLayout.setVerticalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCrearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 130, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Color");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Marca");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Placa");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 220, 20));

        MarcaSelector.setBackground(new java.awt.Color(255, 255, 255));
        MarcaSelector.setEditable(true);
        MarcaSelector.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        MarcaSelector.setForeground(new java.awt.Color(0, 0, 0));
        MarcaSelector.setMaximumRowCount(20);
        MarcaSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la marca" }));
        MarcaSelector.setBorder(null);
        MarcaSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaSelectorActionPerformed(evt);
            }
        });
        jPanel1.add(MarcaSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, -1));

        TipoSelector.setBackground(new java.awt.Color(255, 255, 255));
        TipoSelector.setEditable(true);
        TipoSelector.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TipoSelector.setForeground(new java.awt.Color(0, 0, 0));
        TipoSelector.setMaximumRowCount(20);
        TipoSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo" }));
        TipoSelector.setBorder(null);
        TipoSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoSelectorActionPerformed(evt);
            }
        });
        jPanel1.add(TipoSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, -1));

        errorMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        errorMensaje.setForeground(new java.awt.Color(255, 0, 0));
        errorMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo-de-exclamacion (1).png"))); // NOI18N
        errorMensaje.setText("Error");
        jPanel1.add(errorMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        finalizadoMensaje.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        finalizadoMensaje.setForeground(new java.awt.Color(51, 255, 51));
        finalizadoMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cheque (1).png"))); // NOI18N
        finalizadoMensaje.setText("Vehiculo creado");
        jPanel1.add(finalizadoMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ColorSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorSelectorActionPerformed

    private void placaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placaMouseClicked
        if(placa.getText().equals("Ingrese la placa")){
            placa.setText("");
        }
        placa.setForeground(Color.BLACK);
    }//GEN-LAST:event_placaMouseClicked

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        btnCrear.setBackground(new Color(66, 172, 232));
        crear.setForeground(Color.white);
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        btnCrear.setBackground(new Color(0, 102, 255));
        crear.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCrearMouseExited

    private void MarcaSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaSelectorActionPerformed

    private void TipoSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoSelectorActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if(placa.getText().equals("")){
            placa.setText("Ingrese la placa");
            placa.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        errorMensaje.setVisible(false);
        finalizadoMensaje.setVisible(false);
        String capPlaca=placa.getText();
        if(capPlaca.equals("Ingrese la placa") || !capPlaca.matches("^[A-Z]{3}[0-9]{3}$")){
           errorMensaje.setVisible(true);
           errorMensaje.setText("Placa no valida");
           return;
        }
        
        if(MarcaSelector.getSelectedItem().toString().equals("Seleccione la marca")){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Selecione una marca");
            return;
        }
        
        if(TipoSelector.getSelectedItem().toString().equals("Seleccione un tipo")){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Selecione un tipo");
            return;
        }
        
        if(ColorSelector.getSelectedItem().toString().equals("Seleccione un color")){
            errorMensaje.setVisible(true);
            errorMensaje.setText("Seleccione un color");
            return;
        }
        
        Vehiculos nuevo = new Vehiculos();
        nuevo.setBrands_id(marcas.get(MarcaSelector.getSelectedIndex()-1).getId());
        nuevo.setColors_Id(colores.get(ColorSelector.getSelectedIndex()-1).getId());
        nuevo.setTypes_Id(tipos.get(TipoSelector.getSelectedIndex()-1).getId());
        nuevo.setLicense_plate(capPlaca);
        try {
            daos.crearVehiculo(nuevo);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        finalizadoMensaje.setVisible(true);
        placa.setText("Ingrese la placa");
        placa.setForeground(new Color(153, 153, 153));
        MarcaSelector.setSelectedIndex(0);
        TipoSelector.setSelectedIndex(0);
        ColorSelector.setSelectedIndex(0);
    }//GEN-LAST:event_btnCrearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ColorSelector;
    private javax.swing.JComboBox<String> MarcaSelector;
    private javax.swing.JComboBox<String> TipoSelector;
    private javax.swing.JPanel btnCrear;
    private javax.swing.JLabel crear;
    private javax.swing.JLabel errorMensaje;
    private javax.swing.JLabel finalizadoMensaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField placa;
    // End of variables declaration//GEN-END:variables
}
